name: Deploy PHP API to Apache2 Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 52.66.20.249 >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts

    - name: Deploy files to server
      run: |
        sudo -u www-data rsync -avz --delete-after --exclude='.git' --exclude='.github' ./ ubuntu@52.66.20.249:/var/www/html/UserManagement/

    - name: Restart Apache2 service
      run: |
        ssh ubuntu@52.66.20.249 "sudo systemctl restart apache2"
